version: '3.4'
networks:
   frontend:
   backend:
   


services:
  eventapp1:
    image: eventapp1/catalogapi
    build:
      context: .\EventApp1
      dockerfile: Dockerfile
    environment:
      DataBaseServer: mssqlserver
      DataBaseName: EventDataBase
      DataBaseUser: sa
      DataBasePassword: EventApp(!)
      ExternalBaseUrl: http://localhost:6900
    ports:
      - "6900:80"
    container_name: eventapp1catalogapi
    networks:
      - backend
      - frontend
    depends_on: 
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApp(!)
    ports:
      - "1648:1433"
    container_name: eventsqlserver
    networks:
      - backend
  tokenserver:
     build:
       context: .\TokenServiceApi
       dockerfile: Dockerfile
     image: eventapp/tokenapi
     logging:
       driver: "json-file"
       options:
         max-size: "200k"
         max-file: "10"
     environment:
       ASPNETCORE_ENVIRONMENT: Development
       MvcClient: http://localhost:5310
     ports:
       - "6901:80"
     container_name: tokenserviceapi1
     networks:
       - backend
       - frontend
     depends_on:
       - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: eventapp1/webmvc
    container_name: eventshop
    environment: 
      EventCatalogUrl: http://eventapp1
      IdentityUrl: http://10.0.0.11:6901
      CallBackUrl: http://localhost:5310
    ports:
      - "5310:80"
    networks:
      - frontend
    depends_on:
      - eventapp1





      








