version: '3.4'
networks:
   frontend:
   backend:
   


services:
  eventapp1:
    image: eventapp1/catalogapi
    build:
      context: .\EventApp1
      dockerfile: Dockerfile
    environment:
      DataBaseServer: mssqlserver
      DataBaseName: EventDataBase
      DataBaseUser: sa
      DataBasePassword: EventApp(!)
      ExternalBaseUrl: http://localhost:6900
    ports:
      - "6900:80"
    container_name: eventapp1catalogapi
    networks:
      - backend
      - frontend
    depends_on: 
      - mssqlserver
  cart:
     build:
       context: .\CartApi
       dockerfile: Dockerfile
     image: eventapp/cartapi
     logging:
       driver: "json-file"
       options:
         max-size: "200k"
         max-file: "10"
     environment:
       ASPNETCORE_ENVIRONMENT: Development
       IdentityUrl: http://10.0.0.11:6700
       ConnectionString: basket.data
     ports:
       - "6901:80"
     container_name: carteventapi
     networks:
       - backend
       - frontend
     depends_on:
      - basket.data
      - tokenserver
      - rabbitmq
  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: jewels/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl:  http://10.0.0.11:6901
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "6802:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApp(!)
    ports:
      - "1648:1433"
    container_name: eventsqlserver
    networks:
      - backend
  tokenserver:
     build:
       context: .\TokenServiceApi
       dockerfile: Dockerfile
     image: eventapp/tokenapi
     logging:
       driver: "json-file"
       options:
         max-size: "200k"
         max-file: "10"
     environment:
       ASPNETCORE_ENVIRONMENT: Development
       MvcClient: http://localhost:5310
     ports:
       - "6902:80"
     container_name: tokenserviceapi1
     networks:
       - backend
       - frontend
     depends_on:
       - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: eventapp1/webmvc
    container_name: eventshop
    environment: 
      EventCatalogUrl: http://eventapp1
      IdentityUrl: http://10.0.0.11:6901
      CallBackUrl: http://localhost:5310
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_Lw7mqdSkBGt4ySwkEwtNQE8u001oFleI7B
      StripePrivateKey: sk_test_LcfVqsCaM8ZOHLgmhkizgJhw00HPWiskOm
    ports:
      - "5310:80"
    networks:
      - frontend
    depends_on:
      - eventapp1

  basket.data:
     image: redis
     container_name: basketeventdata
     ports:
       - "6090:6379"
     networks:
       - backend
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: myrabbitmq1
    ports:
      - "15673:15672"
      - "5673:5672"
      - "5674:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - backend




      








